[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  external_node_modules = ["youtube-transcript"]
  node_bundler = "esbuild"
  timeout = 26

[[plugins]]
  package = "@netlify/plugin-nextjs"
